---
- name: Start Caddy on reboot
  become: true
  ignore_errors: true
  ansible.builtin.cron:
    name: "Start Caddy on Reboot"
    special_time: reboot
    job: "caddy start --config /etc/caddy/Caddyfile"

- name: Restart Caddy
  become: true
  ignore_errors: true
  ansible.builtin.shell: |
    caddy stop
    caddy start --config /etc/caddy/Caddyfile