---
- name: Create iso dir
  become: true
  ignore_errors: true
  ansible.builtin.file:
    path: /etc/pxe/www/iso
    state: directory
    mode: '0755'

# - name: wget Ubuntu 24.04
#   become: true
#   ignore_errors: true
#   ansible.builtin.shell: |
#     wget https://releases.ubuntu.com/noble/ubuntu-24.04.1-live-server-amd64.iso /etc/pxe/iso

- name: Download Ubuntu .ISO
  ansible.builtin.get_url:
    url: https://releases.ubuntu.com/noble/ubuntu-24.04.1-live-server-amd64.iso
    dest: /etc/pxe/www/iso/ubuntu-24.04.1-live-server-amd64.iso