---
- name: Create kernel dir
  become: true
  ignore:errors: true
  ansible.builtin.file:
    path: /etc/pxe/kernel
    state: directory
    mode: '0755'

- name: Extract kernel files for NBP boot
  become: true
  ignore:errors: true
  ansible.builtin.shell: |
    sudo mount /etc/pxe/iso/ubuntu-24.04.1-live-server-amd64.iso /mnt
    sudo cp /mnt/casper/vmlinuz /etc/pxe/kernel
    sudo cp /mnt/casper/initrd /etc/pxe/kernel
    sudo umount /mnt