---
- name: Create kernel dir
  become: true
  ignore_errors: true
  ansible.builtin.file:
    path: /etc/pxe/www/kernel/noble/24.04.1
    state: directory
    mode: '0755'

- name: Mount ISO
  become: true
  ignore_errors: true
  ansible.builtin.shell: |
    mount /etc/pxe/www/iso/ubuntu-24.04.1-live-server-amd64.iso /mnt

- name: Extract kernel files for NBP boot
  become: true
  ignore_errors: true
  ansible.builtin.shell: |
    sudo cp /mnt/casper/vmlinuz /etc/pxe/www/kernel/noble/24.04.1/
    sudo cp /mnt/casper/initrd /etc/pxe/www/kernel/noble/24.04.1/
    

- name: Un-Mount ISO
  become: true
  ignore_errors: true
  ansible.builtin.shell: |
    sudo umount /mnt