---
- name: Download user-data
  ansible.builtin.get_url:
    url: https://github.com/xmattehx/linux-imaging/blob/main/config/noble/24.04.1/ubuntu24041/user-data
    dest: /etc/pxe/www/config/noble/24.04.1/ubuntu24041/user-data

- name: Download meta-data
  ansible.builtin.get_url:
    url: https://github.com/xmattehx/linux-imaging/blob/main/config/noble/24.04.1/ubuntu24041/meta-data
    dest: /etc/pxe/www/config/noble/24.04.1/ubuntu24041/meta-data