---
- name: Download autoexec.ipxe
  ansible.builtin.get_url:
    url: https://github.com/xmattehx/linux-imaging/blob/main/boot/autoexec.ipxe
    dest: /etc/pxe/tftp/autoexec.ipxe

- name: Download ipxe.efi
  ansible.builtin.get_url:
    url: https://github.com/xmattehx/linux-imaging/blob/main/boot/ipxe.efi
    dest: /etc/pxe/tftp/ipxe.efi